apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx" # Chỉ định dùng Nginx làm lễ tân
spec:
  rules:
  - host: lab.byn.id.vn # Tên miền bạn đã cấu hình trên Cloudflare
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webapp-service # Thay bằng đúng tên Service của Web trong thư mục k8s của bạn
            port:
              number: 80 # Cổng mà Service của bạn đang lắng nghe