apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wildcard-ingress
spec:
  rules:
  - host: staging.byn.id.vn
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: krakend-service
            port: { number: 80 }