apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: staging.byn.id.vn
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: krakend-service # Đi qua KrakenD
            port:
              number: 80