# 1. Cấu hình krakend.json
apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-config
data:
  krakend.json: |
    {
      "version": 3,
      "name": "GKE API Gateway",
      "port": 8080,
      "endpoints": [
        {
          "endpoint": "/",
          "method": "GET",
          "output_encoding": "no-op",
          "backend": [
            {
              "url_pattern": "/",
              "encoding": "no-op",
              "host": ["http://webapp-service.default.svc.cluster.local:80"]
            }
          ]
        },
        {
          "endpoint": "/api/gateway-test",
          "method": "GET",
          "output_encoding": "no-op",
          "backend": [
            {
              "url_pattern": "/",
              "encoding": "no-op",
              "host": ["http://webapp-service.default.svc.cluster.local:80"]
            }
          ]
        },
        {
          "endpoint": "/promo/{anything}",
          "method": "GET",
          "output_encoding": "no-op",
          "backend": [
            {
              "url_pattern": "/{anything}",
              "encoding": "no-op",
              "host": ["http://promo-service.default.svc.cluster.local:80"]
            }
          ]
        }
      ]
    }
---
# 2. Cài đặt Pod KrakenD
apiVersion: apps/v1
kind: Deployment
metadata:
  name: krakend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: krakend
  template:
    metadata:
      labels:
        app: krakend
    spec:
      containers:
      - name: krakend
        image: devopsfaith/krakend:2.6.0
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: krakend-config-vol
          mountPath: /etc/krakend/
      volumes:
      - name: krakend-config-vol
        configMap:
          name: krakend-config
---
# 3. Mở cổng nội bộ
apiVersion: v1
kind: Service
metadata:
  name: krakend-service
spec:
  selector:
    app: krakend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080