name: CI to Google Artifact Registry

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  id-token: write

jobs:
  # ==========================================
  # JOB 1: ĐÓNG GÓI VÀ ĐẨY IMAGE (Chạy tự động)
  # ==========================================
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: 'projects/451383144811/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
        service_account: 'github-actions-sa@project-e9976a09-db35-49cd-abb.iam.gserviceaccount.com'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker for GCP
      run: |
        gcloud auth configure-docker asia-southeast1-docker.pkg.dev --quiet

    - name: Build and push Docker image
      run: |
        SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
        REPO_URL="asia-southeast1-docker.pkg.dev/project-e9976a09-db35-49cd-abb/webapp-repo/my-web"
        
        docker build -t $REPO_URL:latest -t $REPO_URL:$SHORT_SHA .
        docker push $REPO_URL:latest
        docker push $REPO_URL:$SHORT_SHA

    # --- BOT BÁO LỖI NẾU JOB 1 THẤT BẠI ---
    - name: Send Telegram Alert on Failure
      if: failure()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          ❌ BÁO ĐỘNG ĐỎ CI/CD: Đóng gói Image thất bại!
          👤 Người thao tác: ${{ github.actor }}
          Vào GitHub Actions kiểm tra log ngay sếp ơi!

    # --- BOT BÁO CHỜ DUYỆT KHI JOB 1 XONG ---
    - name: Send Telegram Alert for Approval
      if: success()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          ⏳ YÊU CẦU PHÊ DUYỆT!
          📦 Code đã được đóng gói thành Docker Image an toàn.
          👤 Nhân viên: ${{ github.actor }} đang xin phép đẩy lên Production.
          👉 Sếp vào GitHub check và Approve ngay nhé!!
          🔗 Link: https://github.com/${{ github.repository }}/actions

  # ==========================================
  # JOB 2: CẬP NHẬT K8S (Chờ Sếp Phê Duyệt.)
  # ==========================================
  update-manifest:
    needs: build-and-push-image
    environment: production
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Update Kubernetes Manifest
      run: |
        SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
        sed -i "s|image: asia-southeast1-docker.pkg.dev/project-e9976a09-db35-49cd-abb/webapp-repo/my-web:.*|image: asia-southeast1-docker.pkg.dev/project-e9976a09-db35-49cd-abb/webapp-repo/my-web:$SHORT_SHA|g" k8s/app.yaml
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add k8s/app.yaml
        git commit -m "ci: update image tag to $SHORT_SHA [skip ci]"
        git push

    # --- BOT BÁO THÀNH CÔNG SAU KHI SẾP DUYỆT XONG ---
    - name: Send Telegram Alert on Success
      if: success()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          ✅ TRIỂN KHAI THÀNH CÔNG!
          🚀 Bản cập nhật mới đã được đẩy sang ArgoCD.
          🌐 Môi trường: Production
          🔗 Domain: https://production.byn.id.vn

    # --- BOT BÁO CÁO LỖI NẾU JOB 2 THẤT BẠI ---
    - name: Send Telegram Alert on Deploy Failure
      if: failure()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          🚨 LỖI TRIỂN KHAI PRODUCTION!
          Sếp đã duyệt nhưng quá trình cập nhật cấu hình sang ArgoCD bị thất bại.
          👤 Người duyệt: ${{ github.actor }}
          Vào GitHub Actions kiểm tra log ngay nhé sếp!
          🔗 Link: https://github.com/${{ github.repository }}/actions